object Versions {
    const val gradle_tools = "3.3.0-alpha04"
    const val kotlin = "1.2.60"

    const val azure_mobile = "2.0.3"
    const val azure_storage = "0.7.0"
    const val crashlytics = "2.9.4@aar"
    const val crashlytics_answers = "1.4.1@aar"
    const val faster_xml = "2.7.0"
    const val gms_wearable = "15.0.1"
    const val gson = "2.8.0"
    const val hamcrest = "1.3"
    const val jetbrains_annotations = "15.0"
    const val junit = "4.12"
    const val pebble_kit = "4.0.1"
    const val support_test = "1.0.2"
    const val support = "27.1.1"
    const val wearable = "2.3.0"

    const val material = "1.0.0-beta01"
    const val x_appcompat = "1.0.0-beta01"
    const val x_arch = "2.0.0-alpha1"
    const val x_constraint_layout = "1.1.2"
    const val x_espresso = "3.1.0-alpha1"
    const val x_preference = "1.0.0-alpha1"
    const val x_recyclerview = "1.0.0-alpha1"
    const val x_test = "1.1.0-alpha1"
}

object Libs {
    const val gradle_build_tools = "com.android.tools.build:gradle:${Versions.gradle_tools}"

    const val material = "com.google.android.material:material:${Versions.material}"
    const val x_appcompat = "androidx.appcompat:appcompat:${Versions.x_appcompat}"
    const val x_arch_lifecycle_extensions = "androidx.lifecycle:lifecycle-extensions:${Versions.x_arch}"
    const val x_arch_persistence_room = "androidx.room:room-runtime:${Versions.x_arch}"
    const val x_cardview = "androidx.cardview:cardview:${Versions.x_appcompat}"
    const val x_constraint_layout = "androidx.constraintlayout:constraintlayout:${Versions.x_constraint_layout}"
    const val x_espresso = "androidx.test.espresso:espresso-core:${Versions.x_espresso}"
    const val x_preference = "androidx.preference:preference:${Versions.x_preference}"
    const val x_recyclerview = "androidx.recyclerview:recyclerview:${Versions.x_recyclerview}"
    const val x_test_rules = "androidx.test:rules:${Versions.x_test}"
    const val x_test_runner = "androidx.test:runner:${Versions.x_test}"

    const val azure_mobile = "com.microsoft.azure:azure-mobile-services-android-sdk:${Versions.azure_mobile}"
    const val azure_storage = "com.microsoft.azure.android:azure-storage-android:${Versions.azure_storage}"
    const val crahslytics = "com.crashlytics.sdk.android:crashlytics:${Versions.crashlytics}"
    const val crahslytics_answers = "com.crashlytics.sdk.android:answers:${Versions.crashlytics_answers}"
    const val faster_xml = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv:${Versions.faster_xml}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val hamcrest = "org.hamcrest:hamcrest-library:${Versions.hamcrest}"
    const val jetbrains_annotations = "org.jetbrains:annotations-java5:${Versions.jetbrains_annotations}"
    const val junit = "junit:junit:${Versions.junit}"
    const val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    const val kotlin_plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val support_annotations = "com.android.support:support-annotations:${Versions.support}"
    const val support_appcompat_v7 = "com.android.support:appcompat-v7:${Versions.support}"
    const val support_design = "com.android.support:design:${Versions.support}"
    const val support_preference_v7 = "com.android.support:preference-v7:${Versions.support}"
    const val support_preference_v14 = "com.android.support:preference-v14:${Versions.support}"
    const val support_test_rules = "com.android.support.test:rules:${Versions.support_test}"
    const val support_test_runner = "com.android.support.test:runner:${Versions.support_test}"
    const val support_wear = "com.android.support:wear:${Versions.support}"
    const val support_wearable = "com.google.android.support:wearable:${Versions.wearable}"

    const val wearable = "com.google.android.wearable:wearable:${Versions.wearable}"
    const val gms_wearable = "com.google.android.gms:play-services-wearable:${Versions.gms_wearable}"
    const val pebble_kit = "com.getpebble:pebblekit:${Versions.pebble_kit}"
}
